[package]
name = "cpp_adapter"
version = "3.1.0"
authors = ["Antidote1911 <antidote1911@gmail.com>"]
edition = "2021"

[lib]
name = "cpp_adapter"
crate-type = ["staticlib"]

[dependencies]
shuffle_core = { path = "../shuffle_core" }
