[package]
name = "shuffle_gui"
version = "0.1.0"
edition = "2021"

[dependencies]
egui = "0.31.0"  # Check for the latest version
eframe = "0.31.0"  # Check for the latest version
image = "0.25.5"
shuffle_core = { path = "../shuffle_core" }
