name: Release
permissions:
  contents: write
on:
  push:
    tags:
      - v[0-9]+.*
env:
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -C debuginfo=0 -D warnings
jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: taiki-e/create-gh-release-action@v1
        with:
          branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  upload-assets:
    name: Upload assets (${{ matrix.target }})
    needs: create-release
    strategy:
      matrix:
        include:
          - { os: macos-latest, target: aarch64-apple-darwin }
          - { os: macos-latest, target: x86_64-apple-darwin }
          - { os: ubuntu-latest, target: aarch64-unknown-linux-gnu, tools: binutils-aarch64-linux-gnu }
          - { os: ubuntu-latest, target: aarch64-unknown-linux-musl, tools: binutils-aarch64-linux-gnu }
          - { os: ubuntu-latest, target: armv7-unknown-linux-gnueabihf, tools: binutils-arm-linux-gnueabihf }
          - { os: ubuntu-latest, target: armv7-unknown-linux-musleabihf, tools: binutils-arm-linux-gnueabihf }
          - { os: ubuntu-latest, target: x86_64-unknown-linux-gnu }
          - { os: ubuntu-latest, target: x86_64-unknown-linux-musl }
          - { os: windows-latest, target: aarch64-pc-windows-msvc }
          - { os: windows-latest, target: x86_64-pc-windows-gnu }
          - { os: windows-latest, target: x86_64-pc-windows-msvc }
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Install extra tools
        if: ${{ matrix.tools != '' }}
        run: sudo apt-get install -y --no-install-recommends ${{ matrix.tools }}
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: shuffle
          target: ${{ matrix.target }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  create-checksums:
    name: Create checksums
    needs: upload-assets
    runs-on: ubuntu-latest
    steps:
      - name: Downloads assets
        run: gh release download --repo "${{ github.repository }}" "${{ github.ref_name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create BLAKE2b checksums
        run: b2sum -b *.{gz,zip} > checksums.b2
      - name: Create SHA256 checksums
        run: sha256sum -b *.{gz,zip} > checksums.sha256
      - name: Create SHA512 checksums
        run: sha512sum -b *.{gz,zip} > checksums.sha512
      - name: Upload checksums
        run: gh release upload --clobber --repo "${{ github.repository }}" "${{ github.ref_name }}" checksums.{b2,sha256,sha512}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
